### ISSUE TITLE
Deploy button

### ISSUE THREAD

**Issue by Jerzeydan** [w84death/Tanks-of-Freedom#42] opened 2016-10-25 07:21 UTC
When creating new units, the deploy button doesnt work all the time / is hard to hit

**Comment by czlowiekimadlo** [comment] 2016-10-25 07:40
When spawn point is occupied by a unit, you will not be able to deploy new one - maybe that is your issue. We have to add information about that to the UI, so people know that.

**Comment by Jerzeydan** [comment] 2016-10-25 07:43
That is not my issue. I meant that sometimes when I try to tap the deploy- button, the map square underneath the button is selected instead.

**Comment by czlowiekimadlo** [comment] 2016-10-25 07:44
Ah, then I know where the problem is. Can you tell me which platform are you using? If it is desktop PC, are you using fullscreen?

**Comment by Jerzeydan** [comment] 2016-10-25 07:46
Ah, sorry. I forgot to mention.. I'm playing on Android. Phone is Nexus 6p and android version 7.0

**Comment by czlowiekimadlo** [comment] 2016-10-25 07:48
Hmm, I don't have that issue on my Galaxy tablet, are you using apk from itch.io/Google Play or F-Droid?

**Comment by Jerzeydan** [comment] 2016-10-25 07:48
Google play

**Comment by czlowiekimadlo** [comment] 2016-10-25 07:50
I'll try to reproduce this issue with my device.

**Comment by czlowiekimadlo** [comment] 2016-10-25 07:56
I'm only able to reproduce this while hitting very edge of the button. Overall, on my tablet, it's ok. I'll have to check on a phone, maybe smaller screen makes the button harder to hit.

**Comment by czlowiekimadlo** [comment] 2016-10-27 09:44
After playing some games on my PC I have noticed, that there is some issue with bottom half of the Deploy button bleeding clicks to the map underneath. I'll fix that for 0.6.0-beta and we will see if that helps.

**Comment by czlowiekimadlo** [comment] 2016-10-27 15:59
I just noticed, that android build has overscan allowed - it should not. Please check in game options if you have overscan enabled. If yes, then please turn it off, load a new map and see if issue is still there.

**Comment by cyberbeat** [comment] 2016-10-29 13:17
I had the same problem, it was nearly impossible to hit the deploy button (samsung galaxy s4 mini with cyanogenmod 13 and this game latest release from f-droid store).

Turning off overscan resolved the problem.

**Comment by Jerzeydan** [comment] 2016-10-30 10:37
Disabling overscan fixed the issue! Why the android version even has it?

**Comment by czlowiekimadlo** [comment] 2016-10-30 10:47
It's an oversight with the build configuration - it should not be there. I have already removed it in the master branch, next release will not have that option available.

**Comment by czlowiekimadlo** [comment] 2016-11-03 11:59
Next ToF version, which should be released this month, will have this fixed, so I'm closing this ticket.

**Closed as completed by czlowiekimadlo** 2016-11-03 11:59 UTC

**Comment by cyberbeat** [comment] 2016-11-03 16:39
Thanks!
